spring.application.name=eflora
server.port=8080

# -----------------------
# DATABASE (PostgreSQL)
# -----------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=nick1234
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------
# JPA / HIBERNATE
# -----------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -----------------------
# THYMELEAF
# -----------------------
spring.thymeleaf.cache=false

# -----------------------
# LOGGING
# -----------------------
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# -----------------------
# ACTUATOR
# -----------------------
management.endpoints.web.exposure.include=health,info